name: Deploy to Save Branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
    - name: Copy wwwroot to Save Branch
      run: |
        git checkout -b save
        git add wwwroot
        git commit -m "Save wwwroot content"
        git push origin save

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-save@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./wwwroot
        branch: save
